# Generated by Django 4.1 on 2022-09-20 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie_slag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='slag',
            new_name='slug',
        ),
    ]
