# Generated by Django 4.1 on 2022-09-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0012_director_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='actors',
            field=models.ManyToManyField(to='movie_app.actor'),
        ),
    ]
