# Generated by Django 4.1 on 2022-09-28 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_director_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='actors',
        ),
    ]
