# Generated by Django 4.1 on 2022-09-28 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0016_actor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(null=True, related_name='movies', to='movie_app.actor'),
        ),
    ]
