# Generated by Django 4.1 on 2022-09-28 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0019_dressingroom_alter_movie_actors_actor_dressing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dressingroom',
            old_name='number',
            new_name='room_number',
        ),
    ]
